"""phase8_schema

Revision ID: a2ff58f78e4b
Revises: 
Create Date: 2026-09-22 10:50:04.495511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ff58f78e4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    with op.batch_alter_table('priority_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('escalation_boost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('algorithm_version', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('config_version', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_priority_analysis_complaint_id'), ['complaint_id'], unique=True)

    with op.batch_alter_table('severity_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safety_risk_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('infrastructure_impact_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('public_impact_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('detection_analysis', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('evidence', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('model_version', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('configuration_version', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_severity_analysis_complaint_id'), ['complaint_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('severity_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_severity_analysis_complaint_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('configuration_version')
        batch_op.drop_column('model_version')
        batch_op.drop_column('evidence')
        batch_op.drop_column('detection_analysis')
        batch_op.drop_column('public_impact_score')
        batch_op.drop_column('infrastructure_impact_score')
        batch_op.drop_column('safety_risk_score')

    with op.batch_alter_table('priority_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_analysis_complaint_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('config_version')
        batch_op.drop_column('algorithm_version')
        batch_op.drop_column('escalation_boost')
        batch_op.drop_column('base_score')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
